export type VideoObject = {
  asset_id: string;
  bit_rate: number;
  bytes: number;
  created_at: string;
  duration: number;
  etag: string;
  folder: string;
  format: string;
  frame_rate: number;
  height: number;
  width: number;
  id: string;
  nb_frames: string;
  original_filename: string;
  pages: 0;
  path: string;
  placeholder: boolean;
  playback_url: string;
  public_id: string;
  resource_type: string;
  rotation: number;
  secure_url: string;
  signature: string;
  tags: string[];
  thumbnail_url: string;
  type: string;
  url: string;
  version: number;
  version_id: string;
  video: {
    pix_format: string;
    codec: string;
    level: number;
    profile: string;
    bit_rate: string;
  };
};
